public class __M$Data_Show {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Show"); }
    };
    public static Object showArrayImpl = FFI_STUB;
    public static Object showArrayImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Show.showArrayImpl"); }
    public static Object showCharImpl = FFI_STUB;
    public static Object showCharImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Show.showCharImpl"); }
    public static Object showIntImpl = FFI_STUB;
    public static Object showIntImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Show.showIntImpl"); }
    public static Object showNumberImpl = FFI_STUB;
    public static Object showNumberImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Show.showNumberImpl"); }
    public static Object showStringImpl = FFI_STUB;
    public static Object showStringImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Show.showStringImpl"); }

public static final Object showVoid = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Void.absurd; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showUnit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return "unit"; }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showString = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Show.showStringImpl; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showRecordFieldsNil = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return ""; }; }; return new __Record$73_68_6f_77_52_65_63_6f_72_64_46_69_65_6c_64_73_O(new String[]{"showRecordFields"}, __field0); } }).get();
public static final Object showRecordFields = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("showRecordFields"); };
public static final Object showRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1_i1) -> { return (java.util.function.Function<Object, Object>) (dictShowRecordFields_2_i2) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (record_3_i3) -> { return (((String) ((((String) ("{")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShowRecordFields_2_i2).get("showRecordFields"))).apply(__M$Type_Proxy.__singleton$Proxy.value))).apply(record_3_i3)))))) + ((String) ("}"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }; }; };
public static final Object showProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return "Proxy"; }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showNumber = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Show.showNumberImpl; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showInt = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Show.showIntImpl; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showChar = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Show.showCharImpl; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object showBoolean = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ( ((Boolean) (v_0_i0)) ? "true" : "false"); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get();
public static final Object show = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("show"); };
public static final Object showArray = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (__M$Data_Show.showArrayImpl)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Show.show)).apply(dictShow_0_i0)); return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object showRecordFieldsCons = (java.util.function.Function<Object, Object>) (dictIsSymbol_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictShowRecordFields_1_i1) -> { return (java.util.function.Function<Object, Object>) (dictShow_2_i2) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_3_i3) -> { return (java.util.function.Function<Object, Object>) (record_4_i4) -> { Object key_5_i5 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0_i0).get("reflectSymbol"))).apply(__M$Type_Proxy.__singleton$Proxy.value); return (((String) ((((String) ((((String) ((((String) ((((String) (" ")) + ((String) (key_5_i5))))) + ((String) (": "))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_2_i2).get("show"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeGet)).apply(key_5_i5))).apply(record_4_i4))))))) + ((String) (","))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShowRecordFields_1_i1).get("showRecordFields"))).apply(__M$Type_Proxy.__singleton$Proxy.value))).apply(record_4_i4)))); }; }; return new __Record$73_68_6f_77_52_65_63_6f_72_64_46_69_65_6c_64_73_O(new String[]{"showRecordFields"}, __field0); } }).get(); }; }; };
public static final Object showRecordFieldsConsNil = (java.util.function.Function<Object, Object>) (dictIsSymbol_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictShow_1_i1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2_i2) -> { return (java.util.function.Function<Object, Object>) (record_3_i3) -> { Object key_4_i4 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0_i0).get("reflectSymbol"))).apply(__M$Type_Proxy.__singleton$Proxy.value); return (((String) ((((String) ((((String) ((((String) (" ")) + ((String) (key_4_i4))))) + ((String) (": "))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_1_i1).get("show"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeGet)).apply(key_4_i4))).apply(record_3_i3))))))) + ((String) (" "))); }; }; return new __Record$73_68_6f_77_52_65_63_6f_72_64_46_69_65_6c_64_73_O(new String[]{"showRecordFields"}, __field0); } }).get(); }; };
}
