public class __M$Data_Eq {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Eq"); }
    };
    public static Object eqArrayImpl = FFI_STUB;
    public static Object eqArrayImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Eq.eqArrayImpl"); }
    public static Object eqBooleanImpl = FFI_STUB;
    public static Object eqBooleanImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Eq.eqBooleanImpl"); }
    public static Object eqCharImpl = FFI_STUB;
    public static Object eqCharImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Eq.eqCharImpl"); }
    public static Object eqIntImpl = FFI_STUB;
    public static Object eqIntImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Eq.eqIntImpl"); }
    public static Object eqNumberImpl = FFI_STUB;
    public static Object eqNumberImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Eq.eqNumberImpl"); }
    public static Object eqStringImpl = FFI_STUB;
    public static Object eqStringImpl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Eq.eqStringImpl"); }

public static final Object eqVoid = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return true; }; }; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get();
public static final Object eqUnit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return true; }; }; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get();
public static final Object eqString = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Eq.eqStringImpl; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get();
public static final Object eqRowNil = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return (java.util.function.Function<Object, Object>) (v2_2_i2) -> { return true; }; }; }; return new __Record$65_71_52_65_63_6f_72_64_O(new String[]{"eqRecord"}, __field0); } }).get();
public static final Object eqRecord = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("eqRecord"); };
public static final Object eqRec = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictEqRecord_1_i1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEqRecord_1_i1).get("eqRecord"))).apply(__M$Type_Proxy.__singleton$Proxy.value); return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get(); }; };
public static final Object eqProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return true; }; }; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get();
public static final Object eqNumber = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Eq.eqNumberImpl; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get();
public static final Object eqInt = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Eq.eqIntImpl; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get();
public static final Object eqChar = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Eq.eqCharImpl; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get();
public static final Object eqBoolean = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Eq.eqBooleanImpl; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get();
public static final Object eq1 = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("eq1"); };
public static final Object eq = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("eq"); };
public static final Object eqArray = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (__M$Data_Eq.eqArrayImpl)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(dictEq_0_i0)); return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get(); };
public static final Object eq1Array = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Eq.eqArray)).apply(dictEq_0_i0)); }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get();
public static final Object eqRowCons = (java.util.function.Function<Object, Object>) (dictEqRecord_0_i0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1_i1) -> { return (java.util.function.Function<Object, Object>) (dictIsSymbol_2_i2) -> { return (java.util.function.Function<Object, Object>) (dictEq_3_i3) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_4_i4) -> { return (java.util.function.Function<Object, Object>) (ra_5_i5) -> { return (java.util.function.Function<Object, Object>) (rb_6_i6) -> { Object get_7_i7 = ((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeGet)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_2_i2).get("reflectSymbol"))).apply(__M$Type_Proxy.__singleton$Proxy.value)); return (((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_3_i3).get("eq"))).apply(((java.util.function.Function<Object, Object>) (get_7_i7)).apply(ra_5_i5)))).apply(((java.util.function.Function<Object, Object>) (get_7_i7)).apply(rb_6_i6)))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEqRecord_0_i0).get("eqRecord"))).apply(__M$Type_Proxy.__singleton$Proxy.value))).apply(ra_5_i5))).apply(rb_6_i6)))); }; }; }; return new __Record$65_71_52_65_63_6f_72_64_O(new String[]{"eqRecord"}, __field0); } }).get(); }; }; }; };
public static final Object notEq = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return (java.util.function.Function<Object, Object>) (y_2_i2) -> { return (!(((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_0_i0).get("eq"))).apply(x_1_i1))).apply(y_2_i2))))); }; }; };
public static final Object notEq1 = (java.util.function.Function<Object, Object>) (dictEq1_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictEq_1_i1) -> { return (java.util.function.Function<Object, Object>) (x_2_i2) -> { return (java.util.function.Function<Object, Object>) (y_3_i3) -> { return (!(((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq1_0_i0).get("eq1"))).apply(dictEq_1_i1))).apply(x_2_i2))).apply(y_3_i3))))); }; }; }; };
}
